### ISSUE TITLE
Emit some logging, even in success cases

### ISSUE THREAD

**Issue by jsquyres** [cisco-open/grabit#7]
## Problem Statement

It would be great if `grabit` had the capability to emit some logging, even in successful cases.  

## Proposed Solution

Add some debugging logging for things like:

* Starting a resource download
* Finished a resource download
* Computing a resource checksum
* Checksum matches (there's already an error message if the checksum doesn't match)

The intent of making these be debug messages is that they wouldn't shown by default -- by default, nothing is emitted in the successful case (just like it is today).  But if a user chooses to, they can `-l debug` to see some periodic messages while `grabit` is working.

For extra bonus points: include an "x of y" message in each of these messages, where x is the number of the resources being operated on out of y total resources -- similar to when rpm/yum/dnf installs multiple RPMs.

## Alternatives Considered

Such messages probably aren't "debug" messages, and could therefore be "info" messages.  If that's the case, perhaps the default logging level should be raised to "warn" (instead of "info") such that the messages would still not be emitted by default.

## Additional Context

This would be helpful for `grabit`'s actions will take a while (e.g., when the resources it has to download are large).

**Comment by rabadin** [comment]
I agree that in the non-debug, successful case, nothing should be displayed. But it would be good to be able to have a debug more to show progress indeed.
